import type { KanjiReference } from "@joylingo/shared";

let cache: Record<string, KanjiReference> | null = null;

/** Load bundled KANJIDIC reference (generated by build-kanjidic script). */
export async function loadKanjiReference(): Promise<Record<string, KanjiReference>> {
  if (cache) return cache;
  const res = await fetch("/kanji/reference.json");
  if (!res.ok) throw new Error("Failed to load kanji reference");
  const data = (await res.json()) as KanjiReference[];
  cache = Object.fromEntries(data.map((k) => [k.char, k]));
  return cache;
}

export function lookupKanji(
  ref: Record<string, KanjiReference>,
  char: string,
): KanjiReference | null {
  return ref[char] ?? null;
}
